### ISSUE TITLE
Unable to use aiocouchdb: problem between keyboard and chair

### ISSUE THREAD

**Issue by ronjouch** [aio-libs/aiocouchdb#12]
Hi.

This is not an issue, I'm abusing your issue tracker to ask a newbie question in the absence of a mailing list / IRC channel. Or if taken positively, maybe it can be taken as a hint that the doc could be more helpful to total `asyncio` newcomers; I'll be glad to propose such a doc patch if we end up feeling the need for it.

My humble objective here is to succeed at fetching and printing the `'Welcome!'` Couch message using your `server.info()`.

So after reading the doc, I run my `localhost:5984` couch instance, create a python3.4 virtualenv, pip install aiocouchdb, touch a file, and here's what I try to run:

```python
#! /usr/bin/env python3

import aiocouchdb

server = aiocouchdb.Server()
print('server:', server, '\n')
```

That works (and I'll omit the `import`s and `server` creation for now): it prints `server: <aiocouchdb.v1.server.Server(http://localhost:5984) object at 0x7fcc064c0be0>`. Now, let's try getting my server info. I see the doc mentioning *Python doesn’t supports yield from in shell*, but I don't know better, so I try it anyway:

```python
yield from server.info()
```

Barf, `SyntaxError: 'yield' outside function`. Okay, I can fix that:

```python
def sinfo():
    yield from server.info()

something = sinfo()
print(something)
```

Great, I have a `<generator object sinfo at 0x7fe8e59c13f0>`. Let's `next()` it:

```python
def sinfo():
    yield from server.info()

gen = sinfo()
box = next(gen)
print(box)
```

Yay, a `<Future pending>`. How do I attach a callback to this thing? Thank you, [python 3.4 doc on `add_done_callback`](https://docs.python.org/3.4/library/asyncio-task.html#asyncio.Future.add_done_callback):

```python
def sinfo():
    yield from server.info()

gen = sinfo()
fut = next(gen)
fut.add_done_callback(print)
print(fut)
```

And hey, there's even a nice `__repr__` here to help me see this in my final print: `<Future pending cb=[print()]>`.

But sadly, nothing is printed.

* Am I exiting before receiving anything? Well no, `sleep()`ing for a while doesn't help, and more importantly...
* ... my couchdb log shows no incoming request :-/
* Am I failing to initialize something? I didn't see more required initialization in the doc :/ .Also, I don't see any mention of me needing to do event loop management, and as I see an `asyncio.get_event_loop()` call in `client.py` so I assume it's none of my business.

What am I doing terribly wrong? Sorry again for hijacking your issue tracker, and thanks for your work :)

**Comment by kxepal** [comment]
Hi,

At first I think you need to read about what [asyncio](https://docs.python.org/3/library/asyncio.html) is and [how it works](http://www.snarky.ca/how-the-heck-does-async-await-work-in-python-3-5). This library is not supposed to be used in non-asyncio way without pain.

**Comment by ronjouch** [comment]
Hi. Well I did read about asyncio, I *am* trying to use aiocouchdb in an asyncio way (just need help), and thanks for the article, but it remains painful as a newcomer to get something done with it :-/ .

After some reading ([this article](http://www.giantflyingsaucer.com/blog/?p=5557) helped), I have a start of an answer my initial question *"Am I failing to initialize something? I didn't see more required initialization in the doc :/ .Also, I don't see any mention of me needing to do event loop management, and as I see an `asyncio.get_event_loop()` call in `client.py` so I assume it's none of my business"*...

→ Yes, you need to fire an event loop (in addition to the one that can be seen [in client.py](https://github.com/aio-libs/aiocouchdb/blob/master/aiocouchdb/client.py#L271)? Is it better to pass it when starting the server? I don't know.). 

Anyway, below is what worked for me, and I see my welcome message.

* Caveat: I get `Unclosed connector` / `Exception ignored in` messages and am unsure what kind of exception handling I missed. Doing my work in a `try/except` didn't help, googling didn't either.

```python
import asyncio
import aiocouchdb
server = aiocouchdb.Server()

@asyncio.coroutine
def get_info():
    inf = yield from server.info()
    print(inf)

asyncio.get_event_loop().run_until_complete(get_info())
```

**Comment by kxepal** [comment]
@ronjouch Well, the truth is yours, to start use aiocouchdb you need to have a little bit experience with asyncio and understand how it works. In contrast with [couchdb-python](https://github.com/djc/couchdb-python), which just works (: But there is nothing much to do with that as these are the base things required to know.

> I didn't see more required initialization in the doc 

Hm, I was though that there is the one, but also didn't found any complete example except the one that will not ever work (: Filed #12 about.

> Is it better to pass it when starting the server? I don't know.

Best practice says that better pass the loop explicitly if you can. This could save you from unexpected bugs.


> I get Unclosed connector / Exception ignored in messages and am unsure what kind of exception handling I missed. Doing my work in a try/except didn't help, googling didn't either.

That's a bug, I filled #14 to track this down.

**Comment by ronjouch** [comment]
@kxepal thanks for following up with #13 and #14 :+1: . I'm proposing a simple doc patch for #13. Nothing more to say here, closing this one.
