### ISSUE TITLE
Is this project's still alive?

### ISSUE THREAD

**Issue by mliubchych** [aio-libs/aiocouchdb#18]
It seems that further development is frozen for now (latest commit was in Sep 12, 2016).

Is this project still maintained?

There are few PRs, but I'd be glad to help in near future with development. Can I count on code review from maintainers or should I fork it for my own?

Thanks in advance!

**Comment by kxepal** [comment]
@nlyubchich 
Hi! Good question. I had quite lack of time to maintain it and provide support of modern aiohttp versions. Now I'm getting slowly back to things I left in past days, so yes, it will be returned to maintained state in few next days. 

Any help and PRs are welcome!

**Comment by mliubchych** [comment]
@kxepal, glad to hear! Thanks for your work BTW
