### ISSUE TITLE
Feeds broken against couchbase sync gateway

### ISSUE THREAD

**Issue by ethanfrey** [aio-libs/aiocouchdb#9]
First off, thank you for this project, I'm building an app that should scale quite largely against couchdb and I'm looking forward to using the power of async :)

I had prototype code working perfectly against CouchDb (1.4) and recently we are trying to transition to Couchbase Sync Gateway for scalability issues (we expect thousands of concurrent feeds). After some setup pains, my script to write test data worked, and the web interface returns the list of documents, but all queries with aiocouchdb returned nothing.

I spent quite some time debugging this. And it seems to be a bug in the library, which may well be related to the problem in issue #8 
```curl http://localhost:5984/default/_all_docs?include_docs=true```
 returns the proper information. In this case:
```
{"rows":[
{"key":"product:484d5edd-e8f3-4cbb-962f-c88b08898a4f","id":"product:484d5edd-e8f3-4cbb-962f-c88b08898a4f","value":{"rev":"1-2d78300a38c3f4e8db23e05d9ed20d1d"},"doc":{"_id":"product:484d5edd-e8f3-4cbb-962f-c88b08898a4f","_rev":"1-2d78300a38c3f4e8db23e05d9ed20d1d","created_at":"2016-01-21T14:19:02.627+0000","name":"Pasta","price":750,"type":"product","version":1}}
,{"key":"product:4ab9a3e1-2081-4159-9746-2b1cb29e0cb4","id":"product:4ab9a3e1-2081-4159-9746-2b1cb29e0cb4","value":{"rev":"1-39244db8fbf1150f18ef2b755487068d"},"doc":{"_id":"product:4ab9a3e1-2081-4159-9746-2b1cb29e0cb4","_rev":"1-39244db8fbf1150f18ef2b755487068d","created_at":"2016-01-21T14:01:02.279+0000","name":"Peanuts","price":150,"type":"product","version":1}}
,{"key":"product:7219f59b-3fce-4893-8f38-e2a1f38a82dc","id":"product:7219f59b-3fce-4893-8f38-e2a1f38a82dc","value":{"rev":"1-1bf8bbc9e5b5cc626361f76f14dc29bd"},"doc":{"_id":"product:7219f59b-3fce-4893-8f38-e2a1f38a82dc","_rev":"1-1bf8bbc9e5b5cc626361f76f14dc29bd","created_at":"2016-01-21T13:57:52.495+0000","name":"Beer","price":200,"type":"product","version":1}}
],
"total_rows":3,"update_seq":4}
```

My query code looks something like this:
```
        db = await ensure_db(server, db_name)
        docs = await db.all_docs(include_docs=True)
        with docs:
            rec = await docs.next()
            while rec:
                print_json(rec)
                rec = await docs.next()
```
As I said, this worked against CouchDB, but the first call to docs.next() now returns None....

Digging into the aiocouchdb code code, I put a breakpoint in ViewFeed.next (feeds.py:140) and found that `chunk` was the entire body of the response.  Apparently Sync Gateway buffers the text, making one network IO call, while couchdb sends each chunk in it's own network IO call. And quoting from feeds.py:146-147:
```
        elif chunk.startswith(('{"rows"', ']}')):
            return (yield from self.next())
```
Thus, the chunk is skipped and just moved onto the next one... which doesn't exist, so the result is None, an empty iterator :(

For me, the solution is to no longer depend on the network IO caching behavior of the server, but use a more powerful parser to return one line at a time.  (I think ijson (https://pypi.python.org/pypi/ijson) is a great solution for parsing streaming json, and with optional c libraries, very fast).

My work-around looks something like this:

in views.py, add to the top:
```from .client import HttpStreamResponse```
and on line 50, change:
```resp = yield from request(auth=auth, data=data, params=params)```
to:
```resp = yield from request(auth=auth, data=data, params=params, response_class=HttpStreamResponse)```

in Feed._loop (feeds.py:59), change:
```chunk = yield from self._resp.content.read()```
to
```chunk = yield from self._resp.content.readline()```

This mostly works and parses the rows correctly now, it raises an exception on parsing the remainder in ViewFeed.next (feeds.py:140-149). We have an empty line with `],` but the code only checks for `]}`.  Also, we no longer have `{"total_rows"` with no trailing `}`, but rather `"total_rows"` with no leading `{`.

I could work on a patch here, but I would like some direction from the project maintainer.

* There don't seem to be tests for the feeds in unit test (understandably, as it usually requires a server to test), shall I try to mock something there, or is there a way to run tests against various servers.
* What variants need to be supported (CouchDB 1.4? CouchDB 2.0?  Sync Gateway?)
* Is it acceptable to add requirements that provide more robust streaming json parsing?

Thanks again for the great package, and please let me know how I can contribute.

**Comment by kxepal** [comment]
@ethanfrey 
Thanks for the great report!

You're right about issue source and your changes are absolutely correct: starting from 2.0 CouchDB stops to follow the rule "one object - one chunk" to reduce fragmentation so the current code that relies on that is eventually broken.

> There don't seem to be tests for the feeds in unit test (understandably, as it usually requires a server to test), shall I try to mock something there, or is there a way to run tests against various servers.

I already have tests that works in [two modes](https://github.com/aio-libs/aiocouchdb/blob/master/aiocouchdb/tests/utils.py#L27): mock and couchdb (see also Makefile [check](https://github.com/aio-libs/aiocouchdb/blob/master/Makefile#L60) and [check-couchdb](https://github.com/aio-libs/aiocouchdb/blob/master/Makefile#L66-L68) targets). But I'm not happy with such layout since it's too easy to hide an issue with mock. So I plan to keep only integration tests. At least they proves that everything is really works right.

> What variants need to be supported (CouchDB 1.4? CouchDB 2.0? Sync Gateway?)

I can guarantee support of CouchDB, but not Couchbase products. If you can help with the Sync Gateway - that would be awesome! But I'm not sure how to test it. Is it possible to setup it on travis (at least)?

> Is it acceptable to add requirements that provide more robust streaming json parsing?

That sounds good and reasonable. Would be happy to accept it!

P.S. Sorry for this stupid issue with chunks.

**Comment by ethanfrey** [comment]
Thanks for the fast reply.

I find Couchbase installation and setup not as friendly as couch, but it does claim to scale to 1000's of websocket pull feeds, so we gotta try that route.  I am trying to fully automate a Vagrant box with sync gateway, it's almost there, just needs a few steps manual setup, but then will probably be a reasonable starting point to bring it to Travis CI.

If this fix gets CouchDB 2.0 working as well, even better.  I took a look at ijson, and it is unfortunately not so easy to get it to work with asyncio.  I think I have to copy a module and add a whole lot of yield froms.... But the parsing code is solid and well tested.  When I make a fork/patch there, I can integrate it with aiocouchdb feeds.py.  It will probably be next week or the week after.

For now, I made a fork and got a quick (hacky) work-around that probably only works well with sync gateway and nothing else, so I can get my testing going again.  I need to fix it up all proper soon and will make a pull request then.

Thanks for the tips in testing.  I was looking for a feeds.py module in the tests directory.  Now I know where to start.  And MetaAioTestCase an run_in_loop are nice... I was wondering how to get asyncio tests running with normal test runners, without boilerplate everywhere.

**Comment by kxepal** [comment]
Sorry for a long delay! This should be fixed by 6e63d05. If it still not, please reopen this issue.

**Comment by ethanfrey** [comment]
Hi, and thanks for the fix.  Same idea as the quick hack I made to get it working, but much nicer implemented. I'll try it out today with sync gateway and couchdb (I now test our code against both).

I've been busy with other issues, but on the side have been working on porting ijson to work with asyncio (aiojson).  It is mostly finished, and will allow one to take a stream and feed it into a parser and the iterate through all objects there in a general way.  It is a more fleixible parser and doesn't rely on any peculiarities of the feed format, like one item per line, per chunk, or anything. It should handle any valid json and return parsed sub-objects (like each item of the "rows" array)

I'll let you know when it is ready to use.  The tests pass now, but I want to clean up the edges.  Maybe it would be useful here as well.

**Comment by kxepal** [comment]
Sounds very promising! Will be happy to be a beta user. Let me know if any help will be needed.

**Comment by ethanfrey** [comment]
Tested on sync gateway, and had to make a small fix in the parsing.  Added this as pull request #11 
Please check the pull request.  Thanks.
